CREATE TABLE pidstat_metrics AS
SELECT
    CAST(CONCAT(date_col, ' ', Time) AS TIMESTAMP) AS time,
    CAST(UID AS INTEGER) AS uid,
    CAST(PID AS INTEGER) AS pid,
    CAST("%usr" AS REAL) AS usr_percent,
    CAST("%system" AS REAL) AS system_percent,
    CAST("%guest" AS REAL) AS guest_percent,
    CAST("%wait" AS REAL) AS wait_percent,
    CAST("%CPU" AS REAL) AS cpu_percent,
    CAST(CPU AS INTEGER) AS cpu_core,
    CAST("minflt/s" AS REAL) AS minflt_per_sec,
    CAST("majflt/s" AS REAL) AS majflt_per_sec,
    CAST(VSZ AS BIGINT) AS vsz_kb,
    CAST(RSS AS BIGINT) AS rss_kb,
    CAST("%MEM" AS REAL) AS mem_percent,
    CAST("kB_rd/s" AS REAL) AS kb_read_per_sec,
    CAST("kB_wr/s" AS REAL) AS kb_write_per_sec,
    CAST("kB_ccwr/s" AS REAL) AS kb_cancelled_write_per_sec,
    CAST(iodelay AS INTEGER) AS iodelay_ticks,
    CAST("cswch/s" AS REAL) AS context_switch_per_sec,
    CAST("nvcswch/s" AS REAL) AS nonvoluntary_context_switch_per_sec,
    Command AS command
FROM read_csv(dp('../pidstat/*.tsv'),
    delim = '\t',
    header = false,
    auto_detect = false,
    ignore_errors = true,
    columns = {
        'date_col': 'VARCHAR',
        'Time': 'VARCHAR',
        'UID': 'VARCHAR',
        'PID': 'VARCHAR',
        '%usr': 'VARCHAR',
        '%system': 'VARCHAR',
        '%guest': 'VARCHAR',
        '%wait': 'VARCHAR',
        '%CPU': 'VARCHAR',
        'CPU': 'VARCHAR',
        'minflt/s': 'VARCHAR',
        'majflt/s': 'VARCHAR',
        'VSZ': 'VARCHAR',
        'RSS': 'VARCHAR',
        '%MEM': 'VARCHAR',
        'kB_rd/s': 'VARCHAR',
        'kB_wr/s': 'VARCHAR',
        'kB_ccwr/s': 'VARCHAR',
        'iodelay': 'VARCHAR',
        'cswch/s': 'VARCHAR',
        'nvcswch/s': 'VARCHAR',
        'Command': 'VARCHAR'
    }
)
;